baseURL = "https://alinachen-hessen.github.io/mysite/" 
languageCode = "zh-cn"
title = "我的 Alina site"
theme = "PaperMod"

enableRobotsTXT = true

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = true

