baseURL = "https://alinachen-hessen.github.io/mysite/" 
languageCode = "zh-cn"
title = "我的 Alina site"
theme = "PaperMod"

enableRobotsTXT = true

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowShareButtons = false
  ShowCodeCopyButtons = true

  mainSections = ["posts"]

  # 列表页显示摘要（summary 或自动截取）
  ShowSummary = true

  # 列表页展示封面图（如果文章里设置了 cover.image）
  ShowPostCover = true
